/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefrescosRouteImport } from './routes/refrescos'
import { Route as RecomendacionesRouteImport } from './routes/recomendaciones'
import { Route as CopasRouteImport } from './routes/copas'
import { Route as CoctelesRouteImport } from './routes/cocteles'
import { Route as CervezasRouteImport } from './routes/cervezas'
import { Route as CachimbasRouteImport } from './routes/cachimbas'
import { Route as IndexRouteImport } from './routes/index'

const RefrescosRoute = RefrescosRouteImport.update({
  id: '/refrescos',
  path: '/refrescos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendacionesRoute = RecomendacionesRouteImport.update({
  id: '/recomendaciones',
  path: '/recomendaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CopasRoute = CopasRouteImport.update({
  id: '/copas',
  path: '/copas',
  getParentRoute: () => rootRouteImport,
} as any)
const CoctelesRoute = CoctelesRouteImport.update({
  id: '/cocteles',
  path: '/cocteles',
  getParentRoute: () => rootRouteImport,
} as any)
const CervezasRoute = CervezasRouteImport.update({
  id: '/cervezas',
  path: '/cervezas',
  getParentRoute: () => rootRouteImport,
} as any)
const CachimbasRoute = CachimbasRouteImport.update({
  id: '/cachimbas',
  path: '/cachimbas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cachimbas': typeof CachimbasRoute
  '/cervezas': typeof CervezasRoute
  '/cocteles': typeof CoctelesRoute
  '/copas': typeof CopasRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/refrescos': typeof RefrescosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cachimbas': typeof CachimbasRoute
  '/cervezas': typeof CervezasRoute
  '/cocteles': typeof CoctelesRoute
  '/copas': typeof CopasRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/refrescos': typeof RefrescosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cachimbas': typeof CachimbasRoute
  '/cervezas': typeof CervezasRoute
  '/cocteles': typeof CoctelesRoute
  '/copas': typeof CopasRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/refrescos': typeof RefrescosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cachimbas'
    | '/cervezas'
    | '/cocteles'
    | '/copas'
    | '/recomendaciones'
    | '/refrescos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cachimbas'
    | '/cervezas'
    | '/cocteles'
    | '/copas'
    | '/recomendaciones'
    | '/refrescos'
  id:
    | '__root__'
    | '/'
    | '/cachimbas'
    | '/cervezas'
    | '/cocteles'
    | '/copas'
    | '/recomendaciones'
    | '/refrescos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CachimbasRoute: typeof CachimbasRoute
  CervezasRoute: typeof CervezasRoute
  CoctelesRoute: typeof CoctelesRoute
  CopasRoute: typeof CopasRoute
  RecomendacionesRoute: typeof RecomendacionesRoute
  RefrescosRoute: typeof RefrescosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/refrescos': {
      id: '/refrescos'
      path: '/refrescos'
      fullPath: '/refrescos'
      preLoaderRoute: typeof RefrescosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendaciones': {
      id: '/recomendaciones'
      path: '/recomendaciones'
      fullPath: '/recomendaciones'
      preLoaderRoute: typeof RecomendacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copas': {
      id: '/copas'
      path: '/copas'
      fullPath: '/copas'
      preLoaderRoute: typeof CopasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocteles': {
      id: '/cocteles'
      path: '/cocteles'
      fullPath: '/cocteles'
      preLoaderRoute: typeof CoctelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cervezas': {
      id: '/cervezas'
      path: '/cervezas'
      fullPath: '/cervezas'
      preLoaderRoute: typeof CervezasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cachimbas': {
      id: '/cachimbas'
      path: '/cachimbas'
      fullPath: '/cachimbas'
      preLoaderRoute: typeof CachimbasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CachimbasRoute: CachimbasRoute,
  CervezasRoute: CervezasRoute,
  CoctelesRoute: CoctelesRoute,
  CopasRoute: CopasRoute,
  RecomendacionesRoute: RecomendacionesRoute,
  RefrescosRoute: RefrescosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
